name: Secret Request

on: [push]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request
        run: |
          curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://example.com/api

